### ISSUE TITLE
Fail to run the SMPL-free model

### ISSUE THREAD

**Issue by krahets** [pengHTYX/PSHuman#6]
Following the README, I got:

```sh
ic| len(self.all_images): 1
Traceback (most recent call last):
  File "/mnt/data/home/jinyudong/repos/PSHuman/inference.py", line 221, in <module>
    main(cfg)
  File "/mnt/data/home/jinyudong/repos/PSHuman/inference.py", line 205, in main
    econdata = SMPLDataset(dataset_param, device='cuda')
  File "/mnt/data/home/jinyudong/repos/PSHuman/econdataset.py", line 70, in __init__
    self.smpl_data = SMPLX()
  File "/mnt/data/home/jinyudong/repos/PSHuman/utils/smpl_util.py", line 1033, in __init__
    self.smplx_faces = np.load(self.smplx_faces_path)
  File "/mnt/data/home/jinyudong/programs/miniconda3/envs/pshuman/lib/python3.10/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'smpl_related/smpl_data/smplx_faces.npy'
```

By the way, does the “SMPL-free model” refer to directly predicting the 6-view images from the input image without using SMPL as a condition, meaning it only requires RGB input?

**Comment by krahets** [comment]
```sh
FileNotFoundError: [Errno 2] No such file or directory: 'smpl_related/smpl_data/smplx_faces.npy'
```

Is there anything I was missing?

**Comment by mrpositron** [comment]
Download the SMPL related data from OneDrive as specified in the README
